local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 20.0
   height: 20.0
   resolution: 0.05
   static_map: false
   rolling_window: true
